[package]
name = "alloy-checked-math-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

alloy-checked-math-lint = { path = "../alloy-checked-math-lint" }

[lib]
proc-macro = true
