[workspace]
resolver = "2"

members = [
  "crates/*"
]

[workspace.dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.104", features = ["extra-traits", "fold", "full"] }
derive_more = { version = "2.0.1", features = ["from", "full"] }
