[package]
name = "checked-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
checked-lint = { path = "../checked-lint" }

[lib]
proc-macro = true
